INFO     root:app_info.py:11   TCP    0.0.0.0:4723           0.0.0.0:0              LISTENING       62524

INFO     root:app_info.py:11 成功: 已终止 PID 为 62524 的进程。

INFO     root:app_info.py:11 10

INFO     root:app_info.py:11 package: name='com.xkw.client' versionCode='51' versionName='3.0.18' compileSdkVersion='33' compileSdkVersionCodename='13'

INFO     root:app_info.py:11 launchable-activity: name='com.zxxk.page.main.LauncherActivity'  label='' icon=''

WARNING  urllib3.connectionpool:connectionpool.py:823 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018D34A284C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session