{"uuid": "9a5ff388-8ea1-4e27-b48c-9f8308867732", "befores": [{"name": "common_driver", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.LocationParseError: Failed to parse: http://127.0.0.1:{self.device_info['server_port']}/wd/hub/session\n", "trace": "  File \"C:\\python3.8\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\python3.8\\lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\python3.8\\lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\study\\pythonT\\pyAppium-master\\testcase\\conftest.py\", line 32, in common_driver\n    driver = base_driver.base_driver()\n  File \"C:\\study\\pythonT\\pyAppium-master\\common\\base_driver.py\", line 61, in base_driver\n    driver = webdriver.Remote(\"http://127.0.0.1:{self.device_info['server_port']}/wd/hub\", desired_caps)\n  File \"C:\\python3.8\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 147, in __init__\n    super(WebDriver, self).__init__(\n  File \"C:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\python3.8\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 227, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"C:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"C:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 397, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"C:\\python3.8\\lib\\site-packages\\urllib3\\request.py\", line 79, in request\n    return self.request_encode_body(\n  File \"C:\\python3.8\\lib\\site-packages\\urllib3\\request.py\", line 171, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\python3.8\\lib\\site-packages\\urllib3\\poolmanager.py\", line 324, in urlopen\n    u = parse_url(url)\n  File \"C:\\python3.8\\lib\\site-packages\\urllib3\\util\\url.py\", line 392, in parse_url\n    return six.raise_from(LocationParseError(source_url), None)\n  File \"<string>\", line 3, in raise_from\n"}, "start": 1699539511611, "stop": 1699539512330}], "start": 1699539511611, "stop": 1699539512685}